apiVersion: v1
data:
  REDIS_OUTPUT_KEY: zz229-proj3-output
kind: ConfigMap
metadata:
  creationTimestamp: "2023-02-28T09:17:41Z"
  name: outputkey
  namespace: zz229
  resourceVersion: "4671278"
  uid: 3f0e7ecc-bcad-4918-81e0-435489201718
