apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
    spec:
      containers:
        - name: recommendation-api
          image: crinstaniev/api:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 30510