apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-api-zz229
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: project2-api-zz229
          image: crinstaniev/api:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          # env:
          #   - name: UPDATE_TIMESTAMP
          #     valueFrom:
          #       configMapKeyRef:
          #         name: config
          #         key: UPDATE_TIMESTAMP
          ports:
            - containerPort: 30510
          volumeMounts:
            - name: pv
              mountPath: /app/data
      restartPolicy: Always
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: project2-pvc-zz229
