apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-api-zz229
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: project2-api-zz229
          image: crinstaniev/api:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 30510
          volumeMounts:
            - name: pv
              mountPath: /app/data
      restartPolicy: Always
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: project2-pvc-zz229
