resources:
- pvc.yaml
- service.yaml
- pod.yaml
- deployment.yaml

commonLabels:
  app: recommendation-system

commonAnnotations:
  app: zz229-recommendation-system

configMapGenerator:
- name: config
  env: config.properties
