apiVersion: v1
kind: PersistentVolume
metadata:
  name: project2-pv-zz229
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/zesen/cs401/project-2/code/shared
    type: DirectoryOrCreate
