apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-zz229
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: project2-pv-zz229