# serverless-runtime deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-runtime
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: severless-runtime
          image: crinstaniev/serverless:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: pyfile
              mountPath: "/opt/usermodule.py"
              subPath: pyfile
          env:
            - name: REDIS_HOST
              value: "67.159.94.11"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_INPUT_KEY
              value: "metrics"
            - name: REDIS_OUTPUT_KEY
              valueFrom:
                configMapKeyRef:
                  name: outputkey
                  key: REDIS_OUTPUT_KEY
      volumes:
        - name: pyfile
          configMap:
            name: pyfile
---
# dashboard deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dashboard
          image: crinstaniev/dashboard:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 31510
              name: http
              protocol: TCP
