apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - deployment.yaml
  - service.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: serverless-redis
    $patch: delete
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pyfile
      namespace: zz229
    $patch: delete
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: outputkey
      namespace: zz229
    $patch: delete

commonLabels:
  app: zz229-project3

namePrefix: zz229-

nameSuffix: -proj3

configMapGenerator:
  - name: pyfile
    files:
      - pyfile

  - name: outputkey
    literals:
      - REDIS_OUTPUT_KEY=zz229-proj3-output
